In [2]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
X = np.arange(6).reshape(6, 1)
print(X)



[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [3]:
poly = PolynomialFeatures(3)
print(poly.fit_transform(X))
print(poly.fit_transform(X).shape)




[[  1.   0.   0.   0.]
 [  1.   1.   1.   1.]
 [  1.   2.   4.   8.]
 [  1.   3.   9.  27.]
 [  1.   4.  16.  64.]
 [  1.   5.  25. 125.]]
(6, 4)


In [4]:
X = X.reshape(1, 6)
print(X)
poly = PolynomialFeatures(3)
print(poly.fit_transform(X))
print(poly.fit_transform(X).shape)

[[0 1 2 3 4 5]]
[[  1.   0.   1.   2.   3.   4.   5.   0.   0.   0.   0.   0.   0.   1.
    2.   3.   4.   5.   4.   6.   8.  10.   9.  12.  15.  16.  20.  25.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   1.   2.   3.   4.   5.   4.   6.
    8.  10.   9.  12.  15.  16.  20.  25.   8.  12.  16.  20.  18.  24.
   30.  32.  40.  50.  27.  36.  45.  48.  60.  75.  64.  80. 100. 125.]]
(1, 84)
